export enum OrderStatus {
  CREATED = 'CREATED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAID_AWAITING_PURCHASE = 'PAID_AWAITING_PURCHASE',
  PURCHASED = 'PURCHASED',
  TRACK_CODE_RECEIVED = 'TRACK_CODE_RECEIVED',
  DELIVERY_PAYMENT_PENDING = 'DELIVERY_PAYMENT_PENDING',
  DELIVERY_PAID = 'DELIVERY_PAID',
  DUTY_PAYMENT_PENDING = 'DUTY_PAYMENT_PENDING',
  DUTY_PAID = 'DUTY_PAID',
  DELIVERED = 'DELIVERED',
}
