export enum OrderStatus {
  CREATED = 'CREATED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAID_AWAITING_PURCHASE = 'PAID_AWAITING_PURCHASE',
  PURCHASED = 'PURCHASED',
  TRACK_CODE_RECEIVED = 'TRACK_CODE_RECEIVED',
}
